spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
server:
  port: 8083
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs