spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3305/inventory_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs